args = commandArgs(trailingOnly=TRUE)
indiv = args[1]
bpp = args[2]
vcf = args[3]
tab = args[4]

cat("// In this example we use chromosomes 1-4 from a single individual from the SGDP.",file=bpp,sep="\n",append=TRUE)
cat("// The options suggested here minimize the use of computing resources but can be further tuned (see below).",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("input_file_type = VCF",file=bpp,sep="\n",append=TRUE)
cat(paste("sequence_file_path = ",vcf,sep=""),file=bpp,sep="\n",append=TRUE)
cat("seq_compression_type = gzip",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("// mask_file_path = mask.bed.gz",file=bpp,sep="\n",append=TRUE)
cat("// mask_file_type = BED",file=bpp,sep="\n",append=TRUE)
cat("// mask_compression_type = gzip",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat(paste("tab_file_path = ",tab,sep=""),file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("optimize = true",file=bpp,sep="\n",append=TRUE)
cat("decode = true",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("function_tolerance = 1e-1",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("// Adjust according to the number of CPUs available; h0ere one per chromosome (faster):",file=bpp,sep="\n",append=TRUE)
cat("number_threads = 5",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("number_intervals = 25",file=bpp,sep="\n",append=TRUE)
cat("number_rho_categories = 4",file=bpp,sep="\n",append=TRUE)
cat("rho_var_model = Gamma",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("// Decrease fragment size for overall smaller memory demands during decoding step:",file=bpp,sep="\n",append=TRUE)
cat("fragment_size = 2000000",file=bpp,sep="\n",append=TRUE)
cat("",file=bpp,sep="\n",append=TRUE)
cat("// Parallel decoding will be faster, however, will also use more memory.",file=bpp,sep="\n",append=TRUE)
cat("// The trade-off can be tuned by adjusting the option number_threads above",file=bpp,sep="\n",append=TRUE)
cat("decode_breakpoints_parallel = true",file=bpp,sep="\n",append=TRUE)
